export const navigations = [
  { name: 'Dashboard', path: '/dashboard/default', icon: 'dashboard' },
  // { label: 'PAGES', type: 'label' },
  // {
  //   name: 'Session/Auth',
  //   icon: 'security',
  //   children: [
  //     { name: 'Sign in', iconText: 'SI', path: '/session/signin' },
  //     { name: 'Sign up', iconText: 'SU', path: '/session/signup' },
  //     { name: 'Forgot Password', iconText: 'FP', path: '/session/forgot-password' },
  //     { name: 'Error', iconText: '404', path: '/session/404' },
  //     { name: 'Otp', iconText: 'SU', path: '/session/otp' },
  //   ],
  // },
  // { label: 'Components', type: 'label' },
  {
    name: 'Partners',
    icon: 'people',
    // badge: { value: '30+', color: 'secondary' },
    children: [
      { name: 'Agent', path: '/material/agent', iconText: 'A' },
      { name: 'Onboarding', path: '/material/onboarding', iconText: 'B' },
      // { name: 'Checkbox', path: '/material/checkbox', iconText: 'C' },
      // { name: 'Dialog', path: '/material/dialog', iconText: 'D' },
      // { name: 'Expansion Panel', path: '/material/expansion-panel', iconText: 'E' },
      // { name: 'Form', path: '/material/form', iconText: 'F' },
      // { name: 'Icons', path: '/material/icons', iconText: 'I' },
      // { name: 'Menu', path: '/material/menu', iconText: 'M' },
      // { name: 'Progress', path: '/material/progress', iconText: 'P' },
      // { name: 'Radio', path: '/material/radio', iconText: 'R' },
      // { name: 'Switch', path: '/material/switch', iconText: 'S' },
      // { name: 'Slider', path: '/material/slider', iconText: 'S' },
      // { name: 'Snackbar', path: '/material/snackbar', iconText: 'S' },
      // { name: 'Table', path: '/table', iconText: 'T' },
    ],
  },
  {
    name: 'Pages',
    icon: 'pages',
    children: [
      { name: 'Terms of Use', path: '/material/termsofuse', iconText: 'E' },
      // { name: 'Terms Of Use', path: '/charts/echarts', iconText: 'E' },
      { name: 'Privacy Policy ', path: '/material/privacypolicy', iconText: 'E' },
      { name: 'Agent Agreement', path: '/material/agentagreement', iconText: 'E' },
    ],
  },
  // {
  //   name: 'Lenders',
  //   icon: 'attach_money',
  //   type: 'extLink',
  //   path: 'http://demos.ui-lib.com/matx-react-doc/',
  // },
  { name: 'Lenders', path: '/lenders', iconText: 'T', icon: 'attach_money' },
];
